# Generated by Django 3.1.4 on 2021-01-05 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=30, verbose_name='Plataforma')),
                ('link', models.TextField(verbose_name='Enlace')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('tituloOriginal', models.TextField(verbose_name='Título Original')),
                ('fechaEstreno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1900)])),
                ('imdb', models.CharField(max_length=3, verbose_name='IMDB')),
                ('poster', models.TextField(verbose_name='Póster')),
                ('temporadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('generos', models.ManyToManyField(to='main.Genero')),
                ('streams', models.ManyToManyField(to='main.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('tituloOriginal', models.TextField(verbose_name='Título Original')),
                ('fechaEstreno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1900)])),
                ('imdb', models.CharField(max_length=3, verbose_name='IMDB')),
                ('poster', models.TextField(verbose_name='Póster')),
                ('duracion', models.CharField(max_length=8, verbose_name='Duracion')),
                ('director', models.CharField(max_length=30, verbose_name='Director')),
                ('generos', models.ManyToManyField(to='main.Genero')),
                ('streams', models.ManyToManyField(to='main.Stream')),
            ],
        ),
    ]
